version: '3.8'

services:
  app:
    build:
      args:
        user: jean
        uid: 1000  
      context: ./
      dockerfile: Dockerfile  
    image: mvp4_laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mvp4_laravel

  webserver:
    image: nginx:alpine
    container_name: mvp4_laravel_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mvp4_laravel

  db:
    image: mysql:8
    container_name: mvp4_laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3314:3306"
    volumes:
      - mvp4dbdata:/var/lib/mysql
    networks:
      - mvp4_laravel

networks:
  mvp4_laravel:

volumes:
  mvp4dbdata:
